version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kurt-kumo-test
    user: root
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

